### PR TITLE
Fixed broken readme

### PR DESCRIPTION
**Pull request by haf**
This text was missing.

### CODE REVIEW

**Comment by knocte** [comment]
I guess this only applies to Mac.

**Comment by 7sharp9** [comment]
You don't overwrite it, you add a local install version which will be used is the version is higher than the packaged one.

Its actually installed to:  `/Users/<username>/Library/Application Support/XamarinStudio-5.0/LocalInstall/fsharpbinding`

**Comment by haf** [comment]
When starting XS after doing 'make install' there's no F# support in the program at all, meaning users have to guess that the 'enable' button needs to be clicked.

I'm approaching this as a user, not as a developer.

**Comment by 7sharp9** [comment]
Yes, this is could a bug in mdtool, or something incorrect in the make script.

**Comment by haf** [comment]
Luckily it's easy to reproduce on a clean installation.

Parallels Desktop lets you create clean OS X installations pretty easily, if you need them.

**Comment by rojepp** [comment]
I like this change. I think a blurb should be added about bumping the version number. New users don't know this. Everyone has to do it, and it can be confusing when you don't see your changes after a `make install`.

**Comment by 7sharp9** [comment]
@rojepp True, I do keep the version in master ahead of the released one, most of the time.

**Comment by rojepp** [comment]
That makes sense. But it has happened a lot of times for me personally. And it always takes embarrassingly long time to figure out the cause. ;)

**Comment by 7sharp9** [comment]
Ive merged and updated slightly, if the wording needs refining then feel free to change it :-)

**Comment by knocte** [comment]
@7sharp9 you're specifying a Mac-specific path in a Linux/Mac section, could you reword?

**Comment by haf** [comment]
If you're debugging the makefile, here's the output at the install stage:

```
rm -fr pack/5.8.2/mac-linux/Debug
mono '/Applications/Xamarin Studio.app/Contents/Resources/lib/monodevelop/bin/mdtool.exe' setup pack bin/mac-linux/Debug/FSharpBinding.dll -d:pack/5.8.2/mac-linux/Debug
Xamarin Studio Add-in Setup Utility
Creating package MonoDevelop.FSharpBinding_5.8.2.mpack
mono '/Applications/Xamarin Studio.app/Contents/Resources/lib/monodevelop/bin/mdtool.exe' setup install -y pack/5.8.2/mac-linux/Debug/MonoDevelop.FSharpBinding_5.8.2.mpack
Xamarin Studio Add-in Setup Utility
Installing F# Language Binding v5.8.2

```

**Pull request merged**
