### PR TITLE
vim: highlight all number literal formats

### PR DESCRIPTION
**Pull request by leafgarland**
Update the regex for fsharpNumber to include all number formats, e.g. 123uy, 123s, etc.

### CODE REVIEW

**Comment by leafgarland** [comment]
Sorry, should have mentioned in the title - this is for Vim.

**Comment by kjnilsson** [comment]
thanks for this - apologies for the slow review - appears I am not getting all my github notifications.

**Comment by leafgarland** [comment]
Cheers, glad it was spotted eventually.

**Comment by kjnilsson** [comment]
if it ever takes more than a couple of days again feel free to ping me on github or twitter (@kjnilsson) 

all updates are greatly appreciated but particularly syntax file ones as I don't really know much about them. :)

**Pull request merged**
