### PR TITLE
Adjust gotodefn test to work for multiple files

### PR DESCRIPTION
**Pull request by rneatherway**

### CODE REVIEW

**Comment by rneatherway** [comment]
Xamarin package broken for now.

**Comment by rneatherway** [comment]
@delexi I asked on Stack Exchange about the buffer switching issue, and apparently it is because the command loop won't be executed while a function (here our test) is executing. We can work around this by running the small part that actually updates the visible buffer in the 'wait' function. I've done that here, and your extended test works now.

**Comment by delexi** [comment]
Thank you for following up on that!

Btw, what is the release policy for fsharp-mode? When can we expect to find a version in melpa(-stable) that includes this functionality?

**Comment by rneatherway** [comment]
Basically, I do releases when I get around to it. This includes bumping the version number, updating the changelog and putting a release version into https://github.com/rneatherway/emacs-fsharp-mode-bin. At the moment I would like to get #879 merged, and possible a feature for generating skeleton project files I have been thinking about. I was planning to do a release after that.

**Pull request merged**
